### ISSUE TITLE
call dispatchShortRequest:Delegate on a main thread

### ISSUE THREAD

**Issue by kos9kus** [Lightstreamer/utility-ThreadPool-ios#4]
Hello, 
I face with freezing interface, when pool overflows ( more 4 active invocations ) the interface is freezing.
I saw that the _waitForFreeThread of NSCondition calls wait, but it happens onto the main thread.
please explain me: the LSURLDispatcher executes into the same thread where it was called ? 
How should i call properly to avoid freezing?  In the example project it doesn't show this case, there are work everything on the one thread.
Thanks in advance

**Comment by gianlucabertani** [comment]
If you are using *short* operations, yes, they may wait for a connection thread to be available. You may avoid freezing the main thread by dispatching the start of the operation on a GCD queue, E.g.:

```objective-c
// Somewhere in your initialization code...
_backgroundQueue= dispatch_queue_create("backgroundQueue", DISPATCH_QUEUE_CONCURRENT);

// Where you actually need the connection...
LSURLDispatchOperation *op= [[LSURLDispatcher sharedDispatcher] dispatchShortRequest:req delegate:self];
dispatch_async(_backgroundQueue, ^() {
    [op start];
});
```

Note that this is not the same as directly starting NSURLConnections on the GCD queue, since in that case from the 5th connection on they would always time out. In other words, the intent of LSURLDispatcher is not to provide a generic background connection mechanism, but rather some way to control the limited connection pool of iOS.

**Comment by kos9kus** [comment]
Okey, I got you, Thank you.
I noticed that the delegate  of LSURLDispatcher makes strong reference(  there are retain delegate while initialization ). Why did you do so? How about calling dealloc method of instant of class that uses LSURLDispatcher. It seems it isn't called
Thanks.

**Comment by gianlucabertani** [comment]
Since this library has been developed when ARC did not exist, weak references were not an option. I had to retain the delegate or I could end up crashing the system.

Anyway, the delegate is retained only by operations. If you use the LSURLDispatcher within a class that is itself a delegate of LSURLDispatcher, it's true that you have a retain cycle, but it lives just until the last operation completes or is cancelled. Taking care of canceling any pending operation before your class is released will ensure it gets properly deallocated.

**Comment by gianlucabertani** [comment]
A quick note to let you know the latest version of the library (released just now) is fully ARC-ified. Moreover, request for short and long operations are now fully asynchronous: they won't put the caller to wait if the connection pool is exhausted.

**Comment by kos9kus** [comment]
Thanks a lot for letting me know!
I am grateful!
